// This file was autogenerated from a .proto file, DO NOT EDIT!
import { fetchAdapter } from './fetch-adapter.js'
import * as Types from './types.js'
export type ResultError = { status: 'ERROR', reason: string }

export type ClientParams = {
    baseUrl: string
    retrieveAccessTokenAuth: () => Promise<string | null>
    retrieveGuestAuth: () => Promise<string | null>
    retrieveGuestSensitiveAuth: () => Promise<string | null>
    retrieveLegacyAccessTokenAuth: () => Promise<string | null>
    retrieveUserAuth: () => Promise<string | null>
    encryptCallback: (plain: any) => Promise<any>
    decryptCallback: (encrypted: any) => Promise<any>
    deviceId: string
    checkResult?: true
}
export default (params: ClientParams) => ({
    GetNostrPubKey: async (): Promise<ResultError | ({ status: 'OK' }& Types.UserNostrPubKey)> => {
        const auth = await params.retrieveAccessTokenAuth()
        if (auth === null) throw new Error('retrieveAccessTokenAuth() returned null')
        let finalRoute = '/api/v2/user/pubkey'
        const { data } = await fetchAdapter.get(params.baseUrl + finalRoute, { headers: { 'authorization': auth } })
        if (data.status === 'ERROR' && typeof data.reason === 'string') return data
        if (data.status === 'OK') { 
            const result = data
            if(!params.checkResult) return { status: 'OK', ...result }
            const error = Types.UserNostrPubKeyValidate(result)
            if (error === null) { return { status: 'OK', ...result } } else return { status: 'ERROR', reason: error.message }
        }
        return { status: 'ERROR', reason: 'invalid response' }
    },
    AuthSocket: async (request: Types.AuthSocketClientHello, cb: (v:ResultError | ({ status: 'OK' }& Types.AuthSocketResponse)) => void, abort?: AbortSignal, ws?: { onOpen?: () => void, onClose?: () => void }): Promise<{ close: () => void }> => { 
        let finalRoute = '/socket/auth'
        const auth = await params.retrieveGuestSensitiveAuth()
        if (auth === null) throw new Error('retrieveGuestSensitiveAuth() returned null')
        const socket = new WebSocket(params.baseUrl + finalRoute)
        let closedByClient = false
        abort?.addEventListener('abort', () => { closedByClient = true; socket.close() })
        socket.addEventListener('close', () => { if (!closedByClient) ws?.onClose?.() })
        socket.addEventListener('open', () => {
            ws?.onOpen?.()
            socket.send(JSON.stringify({ body:request, _authorization: auth }))
        })
        socket.addEventListener('message', (event) => {
            const data = JSON.parse(event.data) as ResultError | ({ status: 'OK' }& Types.AuthSocketResponse)
            cb(data)
        })
		return { close: () => { closedByClient = true; socket.close() } }
    },
    GetNostrRelays: async (): Promise<ResultError | ({ status: 'OK' }& Types.NostrRelays)> => {
        const auth = await params.retrieveAccessTokenAuth()
        if (auth === null) throw new Error('retrieveAccessTokenAuth() returned null')
        let finalRoute = '/api/v2/user/relays'
        const { data } = await fetchAdapter.get(params.baseUrl + finalRoute, { headers: { 'authorization': auth } })
        if (data.status === 'ERROR' && typeof data.reason === 'string') return data
        if (data.status === 'OK') { 
            const result = data
            if(!params.checkResult) return { status: 'OK', ...result }
            const error = Types.NostrRelaysValidate(result)
            if (error === null) { return { status: 'OK', ...result } } else return { status: 'ERROR', reason: error.message }
        }
        return { status: 'ERROR', reason: 'invalid response' }
    },
    SignNostrEvent: async (request: Types.NostrSignRequest): Promise<ResultError | ({ status: 'OK' }& Types.NostrSignResponse)> => {
        const auth = await params.retrieveAccessTokenAuth()
        if (auth === null) throw new Error('retrieveAccessTokenAuth() returned null')
        let finalRoute = '/api/v2/user/sign'
        const { data } = await fetchAdapter.post(params.baseUrl + finalRoute, request, { headers: { 'authorization': auth } })
        if (data.status === 'ERROR' && typeof data.reason === 'string') return data
        if (data.status === 'OK') { 
            const result = data
            if(!params.checkResult) return { status: 'OK', ...result }
            const error = Types.NostrSignResponseValidate(result)
            if (error === null) { return { status: 'OK', ...result } } else return { status: 'ERROR', reason: error.message }
        }
        return { status: 'ERROR', reason: 'invalid response' }
    },
    Nip44Decrypt: async (request: Types.Nip44DecryptRequest): Promise<ResultError | ({ status: 'OK' }& Types.Nip44DecryptResponse)> => {
        const auth = await params.retrieveAccessTokenAuth()
        if (auth === null) throw new Error('retrieveAccessTokenAuth() returned null')
        let finalRoute = '/api/v2/user/decrypt'
        const { data } = await fetchAdapter.post(params.baseUrl + finalRoute, request, { headers: { 'authorization': auth } })
        if (data.status === 'ERROR' && typeof data.reason === 'string') return data
        if (data.status === 'OK') { 
            const result = data
            if(!params.checkResult) return { status: 'OK', ...result }
            const error = Types.Nip44DecryptResponseValidate(result)
            if (error === null) { return { status: 'OK', ...result } } else return { status: 'ERROR', reason: error.message }
        }
        return { status: 'ERROR', reason: 'invalid response' }
    },
    Nip44Encrypt: async (request: Types.Nip44EncryptRequest): Promise<ResultError | ({ status: 'OK' }& Types.Nip44EncryptResponse)> => {
        const auth = await params.retrieveAccessTokenAuth()
        if (auth === null) throw new Error('retrieveAccessTokenAuth() returned null')
        let finalRoute = '/api/v2/user/encrypt'
        const { data } = await fetchAdapter.post(params.baseUrl + finalRoute, request, { headers: { 'authorization': auth } })
        if (data.status === 'ERROR' && typeof data.reason === 'string') return data
        if (data.status === 'OK') { 
            const result = data
            if(!params.checkResult) return { status: 'OK', ...result }
            const error = Types.Nip44EncryptResponseValidate(result)
            if (error === null) { return { status: 'OK', ...result } } else return { status: 'ERROR', reason: error.message }
        }
        return { status: 'ERROR', reason: 'invalid response' }
    },
    Nip98Event: async (request: Types.Nip98EventRequest): Promise<ResultError | ({ status: 'OK' }& Types.Nip98EventResponse)> => {
        const auth = await params.retrieveAccessTokenAuth()
        if (auth === null) throw new Error('retrieveAccessTokenAuth() returned null')
        let finalRoute = '/api/v2/user/nip98'
        const { data } = await fetchAdapter.post(params.baseUrl + finalRoute, request, { headers: { 'authorization': auth } })
        if (data.status === 'ERROR' && typeof data.reason === 'string') return data
        if (data.status === 'OK') { 
            const result = data
            if(!params.checkResult) return { status: 'OK', ...result }
            const error = Types.Nip98EventResponseValidate(result)
            if (error === null) { return { status: 'OK', ...result } } else return { status: 'ERROR', reason: error.message }
        }
        return { status: 'ERROR', reason: 'invalid response' }
    },
    MintFromRefreshToken: async (request: Types.MintFromRefreshTokenRequest): Promise<ResultError | ({ status: 'OK' }& Types.TokensData)> => {
        const auth = await params.retrieveGuestAuth()
        if (auth === null) throw new Error('retrieveGuestAuth() returned null')
        let finalRoute = '/api/guest/refresh'
        const { data } = await fetchAdapter.post(params.baseUrl + finalRoute, request, { headers: { 'authorization': auth } })
        if (data.status === 'ERROR' && typeof data.reason === 'string') return data
        if (data.status === 'OK') { 
            const result = data
            if(!params.checkResult) return { status: 'OK', ...result }
            const error = Types.TokensDataValidate(result)
            if (error === null) { return { status: 'OK', ...result } } else return { status: 'ERROR', reason: error.message }
        }
        return { status: 'ERROR', reason: 'invalid response' }
    },
})
