// This file was autogenerated from a .proto file, DO NOT EDIT!

type Request = any;
type Response = any;
export type ResultError = { status: 'ERROR', reason: string }
export type RequestInfo = { rpcName: string, batch: boolean, nostr: boolean, batchSize: number }
export type RequestStats = { startMs:number, start:bigint, parse: bigint, guard: bigint, validate: bigint, handle: bigint }
export type RequestMetric = AuthContext & RequestInfo & RequestStats & { error?: string }
export type GuestContext = {
}
export type GuestMethodInputs = MintFromRefreshToken_Input
export type GuestMethodOutputs = MintFromRefreshToken_Output

export type AccessTokenContext = {
    grant_id: string
}
export type AccessTokenMethodInputs = GetNostrPubKey_Input | GetNostrRelays_Input | SignNostrEvent_Input | Nip44Decrypt_Input | Nip44Encrypt_Input | Nip98Event_Input
export type AccessTokenMethodOutputs = GetNostrPubKey_Output | GetNostrRelays_Output | SignNostrEvent_Output | Nip44Decrypt_Output | Nip44Encrypt_Output | Nip98Event_Output
export type UserContext = {
    user_id: string
}

export type AuthContext = GuestContext |AccessTokenContext


export type GetNostrPubKey_Input = {rpcName:'GetNostrPubKey'}
export type GetNostrPubKey_Output = ResultError | ({ status: 'OK' } & UserNostrPubKey)

export type GetNostrRelays_Input = {rpcName:'GetNostrRelays'}
export type GetNostrRelays_Output = ResultError | ({ status: 'OK' } & NostrRelays)

export type SignNostrEvent_Input = {rpcName:'SignNostrEvent', req: NostrSignRequest}
export type SignNostrEvent_Output = ResultError | ({ status: 'OK' } & NostrSignResponse)

export type Nip44Decrypt_Input = {rpcName:'Nip44Decrypt', req: Nip44DecryptRequest}
export type Nip44Decrypt_Output = ResultError | ({ status: 'OK' } & Nip44DecryptResponse)

export type Nip44Encrypt_Input = {rpcName:'Nip44Encrypt', req: Nip44EncryptRequest}
export type Nip44Encrypt_Output = ResultError | ({ status: 'OK' } & Nip44EncryptResponse)

export type Nip98Event_Input = {rpcName:'Nip98Event', req: Nip98EventRequest}
export type Nip98Event_Output = ResultError | ({ status: 'OK' } & Nip98EventResponse)


export type MintFromRefreshToken_Input = {rpcName:'MintFromRefreshToken', req: MintFromRefreshTokenRequest}
export type MintFromRefreshToken_Output = ResultError | ({ status: 'OK' } & TokensData)

export type ServerMethods = {
    GetNostrPubKey?: (req: GetNostrPubKey_Input & {ctx: AccessTokenContext, requestObject: Request, responseObject: Response }) => Promise<UserNostrPubKey>
    GetNostrRelays?: (req: GetNostrRelays_Input & {ctx: AccessTokenContext, requestObject: Request, responseObject: Response }) => Promise<NostrRelays>
    SignNostrEvent?: (req: SignNostrEvent_Input & {ctx: AccessTokenContext, requestObject: Request, responseObject: Response }) => Promise<NostrSignResponse>
    Nip44Decrypt?: (req: Nip44Decrypt_Input & {ctx: AccessTokenContext, requestObject: Request, responseObject: Response }) => Promise<Nip44DecryptResponse>
    Nip44Encrypt?: (req: Nip44Encrypt_Input & {ctx: AccessTokenContext, requestObject: Request, responseObject: Response }) => Promise<Nip44EncryptResponse>
    Nip98Event?: (req: Nip98Event_Input & {ctx: AccessTokenContext, requestObject: Request, responseObject: Response }) => Promise<Nip98EventResponse>
    MintFromRefreshToken?: (req: MintFromRefreshToken_Input & {ctx: GuestContext, requestObject: Request, responseObject: Response }) => Promise<TokensData>
}

export enum ErrorCode {
    ERROR_CODE_UNSPECIFIED = 'ERROR_CODE_UNSPECIFIED',
    INVALID_SESSION = 'INVALID_SESSION',
    ACCESS_TOKEN_INVALID = 'ACCESS_TOKEN_INVALID',
    ACCESS_TOKEN_EXPIRED = 'ACCESS_TOKEN_EXPIRED',
    ACCESS_FORBIDDEN = 'ACCESS_FORBIDDEN',
    USER_NOT_FOUND = 'USER_NOT_FOUND',
    GRANT_REVOKED = 'GRANT_REVOKED',
    GRANT_NOT_FOUND = 'GRANT_NOT_FOUND',
    CLIENT_BINDING_MISMATCH = 'CLIENT_BINDING_MISMATCH',
    UPDATE_APP_TO_NEW_VERSION = 'UPDATE_APP_TO_NEW_VERSION',
    OTP_INVALID = 'OTP_INVALID',
    OTP_NOT_FOUND_OR_EXPIRED = 'OTP_NOT_FOUND_OR_EXPIRED',
    OTP_ATTEMPTS_EXCEEDED = 'OTP_ATTEMPTS_EXCEEDED',
    REQUEST_TOKEN_NOT_FOUND_OR_EXPIRED = 'REQUEST_TOKEN_NOT_FOUND_OR_EXPIRED',
    REQUEST_TOKEN_INVALID = 'REQUEST_TOKEN_INVALID',
    REFRESH_TOKEN_INVALID = 'REFRESH_TOKEN_INVALID',
    REFRESH_TOKEN_EXPIRED = 'REFRESH_TOKEN_EXPIRED',
    REFRESH_TOKEN_REPLAYED = 'REFRESH_TOKEN_REPLAYED',
    INVALID_INPUT = 'INVALID_INPUT',
    UNKNOWN_ERROR = 'UNKNOWN_ERROR',
}

export type OptionsBaseMessage = {
    allOptionalsAreSet?: true
}

export type Nip44DecryptRequest = {
    ciphertext: string
    pubkey: string
}
export const Nip44DecryptRequestOptionalFields: [] = []
export type Nip44DecryptRequestOptions = OptionsBaseMessage & {
    checkOptionalsAreSet?: []
    pubkey_CustomCheck?: (v: string) => boolean
    ciphertext_CustomCheck?: (v: string) => boolean
}
export const Nip44DecryptRequestValidate = (o?: Nip44DecryptRequest, opts: Nip44DecryptRequestOptions = {}, path: string = 'Nip44DecryptRequest::root.'): Error | null => {
    if (opts.checkOptionalsAreSet && opts.allOptionalsAreSet) return new Error(path + ': only one of checkOptionalsAreSet or allOptionalNonDefault can be set for each message')
    if (typeof o !== 'object' || o === null) return new Error(path + ': object is not an instance of an object or is null')

    if (typeof o.ciphertext !== 'string') return new Error(`${path}.ciphertext: is not a string`)
    if (opts.ciphertext_CustomCheck && !opts.ciphertext_CustomCheck(o.ciphertext)) return new Error(`${path}.ciphertext: custom check failed`)

    if (typeof o.pubkey !== 'string') return new Error(`${path}.pubkey: is not a string`)
    if (opts.pubkey_CustomCheck && !opts.pubkey_CustomCheck(o.pubkey)) return new Error(`${path}.pubkey: custom check failed`)

    return null
}

export type Nip44DecryptResponse = {
    plaintext: string
}
export const Nip44DecryptResponseOptionalFields: [] = []
export type Nip44DecryptResponseOptions = OptionsBaseMessage & {
    checkOptionalsAreSet?: []
    plaintext_CustomCheck?: (v: string) => boolean
}
export const Nip44DecryptResponseValidate = (o?: Nip44DecryptResponse, opts: Nip44DecryptResponseOptions = {}, path: string = 'Nip44DecryptResponse::root.'): Error | null => {
    if (opts.checkOptionalsAreSet && opts.allOptionalsAreSet) return new Error(path + ': only one of checkOptionalsAreSet or allOptionalNonDefault can be set for each message')
    if (typeof o !== 'object' || o === null) return new Error(path + ': object is not an instance of an object or is null')

    if (typeof o.plaintext !== 'string') return new Error(`${path}.plaintext: is not a string`)
    if (opts.plaintext_CustomCheck && !opts.plaintext_CustomCheck(o.plaintext)) return new Error(`${path}.plaintext: custom check failed`)

    return null
}

export type Nip44EncryptResponse = {
    ciphertext: string
}
export const Nip44EncryptResponseOptionalFields: [] = []
export type Nip44EncryptResponseOptions = OptionsBaseMessage & {
    checkOptionalsAreSet?: []
    ciphertext_CustomCheck?: (v: string) => boolean
}
export const Nip44EncryptResponseValidate = (o?: Nip44EncryptResponse, opts: Nip44EncryptResponseOptions = {}, path: string = 'Nip44EncryptResponse::root.'): Error | null => {
    if (opts.checkOptionalsAreSet && opts.allOptionalsAreSet) return new Error(path + ': only one of checkOptionalsAreSet or allOptionalNonDefault can be set for each message')
    if (typeof o !== 'object' || o === null) return new Error(path + ': object is not an instance of an object or is null')

    if (typeof o.ciphertext !== 'string') return new Error(`${path}.ciphertext: is not a string`)
    if (opts.ciphertext_CustomCheck && !opts.ciphertext_CustomCheck(o.ciphertext)) return new Error(`${path}.ciphertext: custom check failed`)

    return null
}

export type UserNostrPubKey = {
    pubkey: string
}
export const UserNostrPubKeyOptionalFields: [] = []
export type UserNostrPubKeyOptions = OptionsBaseMessage & {
    checkOptionalsAreSet?: []
    pubkey_CustomCheck?: (v: string) => boolean
}
export const UserNostrPubKeyValidate = (o?: UserNostrPubKey, opts: UserNostrPubKeyOptions = {}, path: string = 'UserNostrPubKey::root.'): Error | null => {
    if (opts.checkOptionalsAreSet && opts.allOptionalsAreSet) return new Error(path + ': only one of checkOptionalsAreSet or allOptionalNonDefault can be set for each message')
    if (typeof o !== 'object' || o === null) return new Error(path + ': object is not an instance of an object or is null')

    if (typeof o.pubkey !== 'string') return new Error(`${path}.pubkey: is not a string`)
    if (opts.pubkey_CustomCheck && !opts.pubkey_CustomCheck(o.pubkey)) return new Error(`${path}.pubkey: custom check failed`)

    return null
}

export type Nip98EventRequest = {
    url: string
    request_body?: string
    method: string
}
export type Nip98EventRequestOptionalField = 'request_body'
export const Nip98EventRequestOptionalFields: Nip98EventRequestOptionalField[] = ['request_body']
export type Nip98EventRequestOptions = OptionsBaseMessage & {
    checkOptionalsAreSet?: Nip98EventRequestOptionalField[]
    request_body_CustomCheck?: (v?: string) => boolean
    method_CustomCheck?: (v: string) => boolean
    url_CustomCheck?: (v: string) => boolean
}
export const Nip98EventRequestValidate = (o?: Nip98EventRequest, opts: Nip98EventRequestOptions = {}, path: string = 'Nip98EventRequest::root.'): Error | null => {
    if (opts.checkOptionalsAreSet && opts.allOptionalsAreSet) return new Error(path + ': only one of checkOptionalsAreSet or allOptionalNonDefault can be set for each message')
    if (typeof o !== 'object' || o === null) return new Error(path + ': object is not an instance of an object or is null')

    if ((o.request_body || opts.allOptionalsAreSet || opts.checkOptionalsAreSet?.includes('request_body')) && typeof o.request_body !== 'string') return new Error(`${path}.request_body: is not a string`)
    if (opts.request_body_CustomCheck && !opts.request_body_CustomCheck(o.request_body)) return new Error(`${path}.request_body: custom check failed`)

    if (typeof o.method !== 'string') return new Error(`${path}.method: is not a string`)
    if (opts.method_CustomCheck && !opts.method_CustomCheck(o.method)) return new Error(`${path}.method: custom check failed`)

    if (typeof o.url !== 'string') return new Error(`${path}.url: is not a string`)
    if (opts.url_CustomCheck && !opts.url_CustomCheck(o.url)) return new Error(`${path}.url: custom check failed`)

    return null
}

export type Nip44EncryptRequest = {
    plaintext: string
    pubkey: string
}
export const Nip44EncryptRequestOptionalFields: [] = []
export type Nip44EncryptRequestOptions = OptionsBaseMessage & {
    checkOptionalsAreSet?: []
    plaintext_CustomCheck?: (v: string) => boolean
    pubkey_CustomCheck?: (v: string) => boolean
}
export const Nip44EncryptRequestValidate = (o?: Nip44EncryptRequest, opts: Nip44EncryptRequestOptions = {}, path: string = 'Nip44EncryptRequest::root.'): Error | null => {
    if (opts.checkOptionalsAreSet && opts.allOptionalsAreSet) return new Error(path + ': only one of checkOptionalsAreSet or allOptionalNonDefault can be set for each message')
    if (typeof o !== 'object' || o === null) return new Error(path + ': object is not an instance of an object or is null')

    if (typeof o.plaintext !== 'string') return new Error(`${path}.plaintext: is not a string`)
    if (opts.plaintext_CustomCheck && !opts.plaintext_CustomCheck(o.plaintext)) return new Error(`${path}.plaintext: custom check failed`)

    if (typeof o.pubkey !== 'string') return new Error(`${path}.pubkey: is not a string`)
    if (opts.pubkey_CustomCheck && !opts.pubkey_CustomCheck(o.pubkey)) return new Error(`${path}.pubkey: custom check failed`)

    return null
}

export type MintFromRefreshTokenRequest = {
    refresh_token: string
}
export const MintFromRefreshTokenRequestOptionalFields: [] = []
export type MintFromRefreshTokenRequestOptions = OptionsBaseMessage & {
    checkOptionalsAreSet?: []
    refresh_token_CustomCheck?: (v: string) => boolean
}
export const MintFromRefreshTokenRequestValidate = (o?: MintFromRefreshTokenRequest, opts: MintFromRefreshTokenRequestOptions = {}, path: string = 'MintFromRefreshTokenRequest::root.'): Error | null => {
    if (opts.checkOptionalsAreSet && opts.allOptionalsAreSet) return new Error(path + ': only one of checkOptionalsAreSet or allOptionalNonDefault can be set for each message')
    if (typeof o !== 'object' || o === null) return new Error(path + ': object is not an instance of an object or is null')

    if (typeof o.refresh_token !== 'string') return new Error(`${path}.refresh_token: is not a string`)
    if (opts.refresh_token_CustomCheck && !opts.refresh_token_CustomCheck(o.refresh_token)) return new Error(`${path}.refresh_token: custom check failed`)

    return null
}

export type AuthSocketAuthRequestTokenResponse = {
    expires_at: number
    request_token: string
}
export const AuthSocketAuthRequestTokenResponseOptionalFields: [] = []
export type AuthSocketAuthRequestTokenResponseOptions = OptionsBaseMessage & {
    checkOptionalsAreSet?: []
    expires_at_CustomCheck?: (v: number) => boolean
    request_token_CustomCheck?: (v: string) => boolean
}
export const AuthSocketAuthRequestTokenResponseValidate = (o?: AuthSocketAuthRequestTokenResponse, opts: AuthSocketAuthRequestTokenResponseOptions = {}, path: string = 'AuthSocketAuthRequestTokenResponse::root.'): Error | null => {
    if (opts.checkOptionalsAreSet && opts.allOptionalsAreSet) return new Error(path + ': only one of checkOptionalsAreSet or allOptionalNonDefault can be set for each message')
    if (typeof o !== 'object' || o === null) return new Error(path + ': object is not an instance of an object or is null')

    if (typeof o.expires_at !== 'number') return new Error(`${path}.expires_at: is not a number`)
    if (opts.expires_at_CustomCheck && !opts.expires_at_CustomCheck(o.expires_at)) return new Error(`${path}.expires_at: custom check failed`)

    if (typeof o.request_token !== 'string') return new Error(`${path}.request_token: is not a string`)
    if (opts.request_token_CustomCheck && !opts.request_token_CustomCheck(o.request_token)) return new Error(`${path}.request_token: custom check failed`)

    return null
}

export type AuthSocketClientHello = {
    client_key: string
    protocol_version: number
    request_token?: string
}
export type AuthSocketClientHelloOptionalField = 'request_token'
export const AuthSocketClientHelloOptionalFields: AuthSocketClientHelloOptionalField[] = ['request_token']
export type AuthSocketClientHelloOptions = OptionsBaseMessage & {
    checkOptionalsAreSet?: AuthSocketClientHelloOptionalField[]
    client_key_CustomCheck?: (v: string) => boolean
    protocol_version_CustomCheck?: (v: number) => boolean
    request_token_CustomCheck?: (v?: string) => boolean
}
export const AuthSocketClientHelloValidate = (o?: AuthSocketClientHello, opts: AuthSocketClientHelloOptions = {}, path: string = 'AuthSocketClientHello::root.'): Error | null => {
    if (opts.checkOptionalsAreSet && opts.allOptionalsAreSet) return new Error(path + ': only one of checkOptionalsAreSet or allOptionalNonDefault can be set for each message')
    if (typeof o !== 'object' || o === null) return new Error(path + ': object is not an instance of an object or is null')

    if (typeof o.client_key !== 'string') return new Error(`${path}.client_key: is not a string`)
    if (opts.client_key_CustomCheck && !opts.client_key_CustomCheck(o.client_key)) return new Error(`${path}.client_key: custom check failed`)

    if (typeof o.protocol_version !== 'number') return new Error(`${path}.protocol_version: is not a number`)
    if (opts.protocol_version_CustomCheck && !opts.protocol_version_CustomCheck(o.protocol_version)) return new Error(`${path}.protocol_version: custom check failed`)

    if ((o.request_token || opts.allOptionalsAreSet || opts.checkOptionalsAreSet?.includes('request_token')) && typeof o.request_token !== 'string') return new Error(`${path}.request_token: is not a string`)
    if (opts.request_token_CustomCheck && !opts.request_token_CustomCheck(o.request_token)) return new Error(`${path}.request_token: custom check failed`)

    return null
}

export type AuthSocketResponse = {
    payload: AuthSocketResponse_payload
}
export const AuthSocketResponseOptionalFields: [] = []
export type AuthSocketResponseOptions = OptionsBaseMessage & {
    checkOptionalsAreSet?: []
    payload_Options?: AuthSocketResponse_payloadOptions
}
export const AuthSocketResponseValidate = (o?: AuthSocketResponse, opts: AuthSocketResponseOptions = {}, path: string = 'AuthSocketResponse::root.'): Error | null => {
    if (opts.checkOptionalsAreSet && opts.allOptionalsAreSet) return new Error(path + ': only one of checkOptionalsAreSet or allOptionalNonDefault can be set for each message')
    if (typeof o !== 'object' || o === null) return new Error(path + ': object is not an instance of an object or is null')

    const payloadErr = AuthSocketResponse_payloadValidate(o.payload, opts.payload_Options, `${path}.payload`)
    if (payloadErr !== null) return payloadErr
    

    return null
}

export type Empty = {
}
export const EmptyOptionalFields: [] = []
export type EmptyOptions = OptionsBaseMessage & {
    checkOptionalsAreSet?: []
}
export const EmptyValidate = (o?: Empty, opts: EmptyOptions = {}, path: string = 'Empty::root.'): Error | null => {
    if (opts.checkOptionalsAreSet && opts.allOptionalsAreSet) return new Error(path + ': only one of checkOptionalsAreSet or allOptionalNonDefault can be set for each message')
    if (typeof o !== 'object' || o === null) return new Error(path + ': object is not an instance of an object or is null')

    return null
}

export type NostrRelays = {
    relays: Record<string, RelayPolicy>
}
export const NostrRelaysOptionalFields: [] = []
export type NostrRelaysOptions = OptionsBaseMessage & {
    checkOptionalsAreSet?: []
    relays_EntryOptions?: RelayPolicyOptions
    relays_CustomCheck?: (v: Record<string, RelayPolicy>) => boolean
}
export const NostrRelaysValidate = (o?: NostrRelays, opts: NostrRelaysOptions = {}, path: string = 'NostrRelays::root.'): Error | null => {
    if (opts.checkOptionalsAreSet && opts.allOptionalsAreSet) return new Error(path + ': only one of checkOptionalsAreSet or allOptionalNonDefault can be set for each message')
    if (typeof o !== 'object' || o === null) return new Error(path + ': object is not an instance of an object or is null')

    if (typeof o.relays !== 'object' || o.relays === null) return new Error(`${path}.relays: is not an object or is null`)
    for (const key in o.relays) {
        const relaysErr = RelayPolicyValidate(o.relays[key], opts.relays_EntryOptions, `${path}.relays['${key}']`)
        if (relaysErr !== null) return relaysErr
    }

    return null
}

export type NostrSignRequest = {
    usignedEvent: string
}
export const NostrSignRequestOptionalFields: [] = []
export type NostrSignRequestOptions = OptionsBaseMessage & {
    checkOptionalsAreSet?: []
    usignedEvent_CustomCheck?: (v: string) => boolean
}
export const NostrSignRequestValidate = (o?: NostrSignRequest, opts: NostrSignRequestOptions = {}, path: string = 'NostrSignRequest::root.'): Error | null => {
    if (opts.checkOptionalsAreSet && opts.allOptionalsAreSet) return new Error(path + ': only one of checkOptionalsAreSet or allOptionalNonDefault can be set for each message')
    if (typeof o !== 'object' || o === null) return new Error(path + ': object is not an instance of an object or is null')

    if (typeof o.usignedEvent !== 'string') return new Error(`${path}.usignedEvent: is not a string`)
    if (opts.usignedEvent_CustomCheck && !opts.usignedEvent_CustomCheck(o.usignedEvent)) return new Error(`${path}.usignedEvent: custom check failed`)

    return null
}

export type NostrSignResponse = {
    signedEvent: string
}
export const NostrSignResponseOptionalFields: [] = []
export type NostrSignResponseOptions = OptionsBaseMessage & {
    checkOptionalsAreSet?: []
    signedEvent_CustomCheck?: (v: string) => boolean
}
export const NostrSignResponseValidate = (o?: NostrSignResponse, opts: NostrSignResponseOptions = {}, path: string = 'NostrSignResponse::root.'): Error | null => {
    if (opts.checkOptionalsAreSet && opts.allOptionalsAreSet) return new Error(path + ': only one of checkOptionalsAreSet or allOptionalNonDefault can be set for each message')
    if (typeof o !== 'object' || o === null) return new Error(path + ': object is not an instance of an object or is null')

    if (typeof o.signedEvent !== 'string') return new Error(`${path}.signedEvent: is not a string`)
    if (opts.signedEvent_CustomCheck && !opts.signedEvent_CustomCheck(o.signedEvent)) return new Error(`${path}.signedEvent: custom check failed`)

    return null
}

export type RelayPolicy = {
    read: boolean
    write: boolean
}
export const RelayPolicyOptionalFields: [] = []
export type RelayPolicyOptions = OptionsBaseMessage & {
    checkOptionalsAreSet?: []
    read_CustomCheck?: (v: boolean) => boolean
    write_CustomCheck?: (v: boolean) => boolean
}
export const RelayPolicyValidate = (o?: RelayPolicy, opts: RelayPolicyOptions = {}, path: string = 'RelayPolicy::root.'): Error | null => {
    if (opts.checkOptionalsAreSet && opts.allOptionalsAreSet) return new Error(path + ': only one of checkOptionalsAreSet or allOptionalNonDefault can be set for each message')
    if (typeof o !== 'object' || o === null) return new Error(path + ': object is not an instance of an object or is null')

    if (typeof o.read !== 'boolean') return new Error(`${path}.read: is not a boolean`)
    if (opts.read_CustomCheck && !opts.read_CustomCheck(o.read)) return new Error(`${path}.read: custom check failed`)

    if (typeof o.write !== 'boolean') return new Error(`${path}.write: is not a boolean`)
    if (opts.write_CustomCheck && !opts.write_CustomCheck(o.write)) return new Error(`${path}.write: custom check failed`)

    return null
}

export type Nip98EventResponse = {
    authorization_header: string
}
export const Nip98EventResponseOptionalFields: [] = []
export type Nip98EventResponseOptions = OptionsBaseMessage & {
    checkOptionalsAreSet?: []
    authorization_header_CustomCheck?: (v: string) => boolean
}
export const Nip98EventResponseValidate = (o?: Nip98EventResponse, opts: Nip98EventResponseOptions = {}, path: string = 'Nip98EventResponse::root.'): Error | null => {
    if (opts.checkOptionalsAreSet && opts.allOptionalsAreSet) return new Error(path + ': only one of checkOptionalsAreSet or allOptionalNonDefault can be set for each message')
    if (typeof o !== 'object' || o === null) return new Error(path + ': object is not an instance of an object or is null')

    if (typeof o.authorization_header !== 'string') return new Error(`${path}.authorization_header: is not a string`)
    if (opts.authorization_header_CustomCheck && !opts.authorization_header_CustomCheck(o.authorization_header)) return new Error(`${path}.authorization_header: custom check failed`)

    return null
}

export type TokensData = {
    access_token: string
    refresh_token: string
    expires_at: number
    refresh_expires_at: number
    identifier: string
    account_identifier: string
}
export const TokensDataOptionalFields: [] = []
export type TokensDataOptions = OptionsBaseMessage & {
    checkOptionalsAreSet?: []
    access_token_CustomCheck?: (v: string) => boolean
    refresh_token_CustomCheck?: (v: string) => boolean
    expires_at_CustomCheck?: (v: number) => boolean
    refresh_expires_at_CustomCheck?: (v: number) => boolean
    identifier_CustomCheck?: (v: string) => boolean
    account_identifier_CustomCheck?: (v: string) => boolean
}
export const TokensDataValidate = (o?: TokensData, opts: TokensDataOptions = {}, path: string = 'TokensData::root.'): Error | null => {
    if (opts.checkOptionalsAreSet && opts.allOptionalsAreSet) return new Error(path + ': only one of checkOptionalsAreSet or allOptionalNonDefault can be set for each message')
    if (typeof o !== 'object' || o === null) return new Error(path + ': object is not an instance of an object or is null')

    if (typeof o.account_identifier !== 'string') return new Error(`${path}.account_identifier: is not a string`)
    if (opts.account_identifier_CustomCheck && !opts.account_identifier_CustomCheck(o.account_identifier)) return new Error(`${path}.account_identifier: custom check failed`)

    if (typeof o.access_token !== 'string') return new Error(`${path}.access_token: is not a string`)
    if (opts.access_token_CustomCheck && !opts.access_token_CustomCheck(o.access_token)) return new Error(`${path}.access_token: custom check failed`)

    if (typeof o.refresh_token !== 'string') return new Error(`${path}.refresh_token: is not a string`)
    if (opts.refresh_token_CustomCheck && !opts.refresh_token_CustomCheck(o.refresh_token)) return new Error(`${path}.refresh_token: custom check failed`)

    if (typeof o.expires_at !== 'number') return new Error(`${path}.expires_at: is not a number`)
    if (opts.expires_at_CustomCheck && !opts.expires_at_CustomCheck(o.expires_at)) return new Error(`${path}.expires_at: custom check failed`)

    if (typeof o.refresh_expires_at !== 'number') return new Error(`${path}.refresh_expires_at: is not a number`)
    if (opts.refresh_expires_at_CustomCheck && !opts.refresh_expires_at_CustomCheck(o.refresh_expires_at)) return new Error(`${path}.refresh_expires_at: custom check failed`)

    if (typeof o.identifier !== 'string') return new Error(`${path}.identifier: is not a string`)
    if (opts.identifier_CustomCheck && !opts.identifier_CustomCheck(o.identifier)) return new Error(`${path}.identifier: custom check failed`)

    return null
}





export enum AuthSocketResponse_payload_type {
    REQUEST_TOKEN = 'request_token',
    TOKENS = 'tokens',
}
export const enumCheckAuthSocketResponse_payload_type = (e?: AuthSocketResponse_payload_type): boolean => {
    for (const v in AuthSocketResponse_payload_type) if (e === v) return true
    return false
}
export type AuthSocketResponse_payload = 
    {type:AuthSocketResponse_payload_type.REQUEST_TOKEN, request_token:AuthSocketAuthRequestTokenResponse}|
    {type:AuthSocketResponse_payload_type.TOKENS, tokens:TokensData}

export type AuthSocketResponse_payloadOptions = {
    request_token_Options?: AuthSocketAuthRequestTokenResponseOptions
    tokens_Options?: TokensDataOptions
}
export const AuthSocketResponse_payloadValidate = (o?: AuthSocketResponse_payload, opts:AuthSocketResponse_payloadOptions = {}, path: string = 'AuthSocketResponse_payload::root.'): Error | null => {
    if (typeof o !== 'object' || o === null) return new Error(path + ': object is not an instance of an object or is null')
    const stringType: string = o.type
    switch (o.type) {
        case AuthSocketResponse_payload_type.REQUEST_TOKEN:
        const request_tokenErr = AuthSocketAuthRequestTokenResponseValidate(o.request_token, opts.request_token_Options, `${path}.request_token`)
        if (request_tokenErr !== null) return request_tokenErr
        

        break
        case AuthSocketResponse_payload_type.TOKENS:
        const tokensErr = TokensDataValidate(o.tokens, opts.tokens_Options, `${path}.tokens`)
        if (tokensErr !== null) return tokensErr
        

        break
        default:
            return new Error(path + ': unknown type '+ stringType)
    }
    return null
}
